# TODO
version: '3'
services:

  frontend:
    image: christofferreitz/frontend:latest
    ports:
      - "8082:8080"
    depends_on:
      - backend
    #networks:
    # - backendnetwork
    environment:
      - BACKEND_DNS=backend

  backend:
    image: christofferreitz/backend:latest
    ports:
      - "9000:9000"
<<<<<<< HEAD
    #networks:
    #  - backendnetwork
=======
>>>>>>> 0620f41 (update)
