name: Continuous Integration

on:
#on pull checks if the vode works 
  pull_request:
    branches:
      - main
# on push: checks the code being pushed
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: frontend build
        working-directory: frontend
        run: go build
      - name: running test
        working-directory: frontend
        run: go test ./...