name: Continuous Integration

on:
# on pull checks if the vode works 
  pull_request:
    branches:
      - main
      - 03co
# on push: checks the code being pushed
  push:
    branches:
      - main
      - 03co

jobs:
  build-and-test-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: frontend build
        working-directory: frontend
        run: go build

      - name: running test
        working-directory: frontend
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          dockerfile: Dockerfile
          push: true
          tags: christofferreitz/frontend:latest
          uses: docker/build-push-action@v2
          
      - name: Verify Image Pull
        run: docker images
          
      - name: Run Deploy
        run: docker run -d -p 9000:9000 christofferreitz/frontend:latest

      - name: Run test
        working-directory: testing
        run: bash testing.sh

  build-and-test-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: backend build
        working-directory: backend
        run: go build

      - name: running test
        working-directory: backend
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: christofferreitz/backend:latest
          uses: docker/build-push-action@v2
          
      - name: Verify Image Pull
        run: docker images
          
      - name: Run Deploy
        run: docker run -d -p 9000:9000 christofferreitz/backend:latest


